/* Generated by tools/build_public_ai_grounding.py. Do not edit manually. */
export const PUBLIC_AI_GROUNDING_SHA256 = "90533a29fd566df24680317bfb84efc8c0c46eb08fb157c199aa59bf8fe05cfe";
export const PUBLIC_AI_GROUNDING = Object.freeze(
{
  "artifact_id": "public-ai-grounding-v0",
  "claims": [
    {
      "evidence": [
        "source.orcid.public_record",
        "source.katru.faculty_profile",
        "source.owner_approval.kazakh_display_name"
      ],
      "id": "identity.name",
      "kind": "identity",
      "languages": [
        "en",
        "ru",
        "kk"
      ],
      "presentation_notes": "The English and Russian identity forms remain supported by reviewed public profiles. The repository owner approved the exact Kazakh display form Қорабаев Ескендір Қазбекұлы on 2026-08-23. The claim remains partially_verified because the Kazakh form has not been independently verified through a suitable public authority. Source-specific abbreviated author strings are not silently normalized by this identity decision.",
      "status": "partially_verified",
      "value": {
        "kk_full_name": "Қорабаев Ескендір Қазбекұлы",
        "preferred_public_name": "Iskander Kurabayev",
        "ru_full_name": "Курабаев Искандер Казбекович"
      },
      "verified_at": "2026-08-23"
    },
    {
      "evidence": [
        "source.katru.faculty_profile",
        "source.astana_energy.board_profile"
      ],
      "id": "education.phd.electrical_complexes_systems",
      "kind": "education",
      "presentation_notes": "The bounded degree and field are confirmed by official institutional profiles. Institution, dates, honours, dissertation title, document identifiers, and unrelated biographical details are intentionally not recorded.",
      "status": "verified_public",
      "value": {
        "credential": "PhD",
        "field": "Electrical complexes and systems"
      },
      "verified_at": "2026-08-10"
    },
    {
      "evidence": [
        "source.katru.faculty_profile",
        "source.astana_energy.board_profile"
      ],
      "id": "education.master.electrical_power_engineering",
      "kind": "education",
      "presentation_notes": "The bounded degree and field are confirmed by official institutional profiles. Institution, dates, honours, document identifiers, and unrelated biographical details are intentionally not recorded.",
      "status": "verified_public",
      "value": {
        "credential": "Master of Technical Sciences",
        "field": "Electrical Power Engineering"
      },
      "verified_at": "2026-08-10"
    },
    {
      "evidence": [
        "source.katru.faculty_profile",
        "source.astana_energy.board_profile"
      ],
      "id": "education.specialist.industrial_power_supply",
      "kind": "education",
      "presentation_notes": "The bounded qualification and field are confirmed by official institutional profiles. Institution, dates, honours, document identifiers, and unrelated biographical details are intentionally not recorded.",
      "status": "verified_public",
      "value": {
        "credential": "Specialist degree",
        "field": "Industrial power supply",
        "qualification": "Engineer-electrician"
      },
      "verified_at": "2026-08-10"
    },
    {
      "evidence": [
        "source.katru.faculty_profile",
        "source.astana_energy.board_profile"
      ],
      "id": "role.university.current",
      "kind": "professional_role",
      "presentation_notes": "KATRU, as the employer source, gives 2023-09-01. Astana-Energy's official board biography gives January 2023. This official-source conflict must be resolved or owner-reviewed before changing production timeline wording; v0.1 retains the employer-source date as the primary structured value.",
      "status": "partially_verified",
      "value": {
        "current_as_of": "2026-08-09",
        "organization": "S. Seifullin Kazakh Agrotechnical Research University",
        "role": "Senior Lecturer",
        "since": "2023-09-01"
      },
      "verified_at": "2026-08-09"
    },
    {
      "evidence": [
        "source.astana_energy.board_profile"
      ],
      "id": "role.astana_energy.current",
      "kind": "professional_role",
      "presentation_notes": "The official board page confirms the role and January 2024 election. Recheck currentness before future publication updates.",
      "status": "verified_public",
      "value": {
        "current_as_of": "2026-08-09",
        "elected": "2024-01",
        "organization": "Astana-Energy JSC",
        "role": "Independent Director and Board Member"
      },
      "verified_at": "2026-08-09"
    },
    {
      "evidence": [
        "source.orcid.public_record"
      ],
      "id": "profile.orcid",
      "kind": "academic_profile",
      "presentation_notes": "Use for identity and profile routing only; do not infer publication completeness, metrics, or current affiliation.",
      "status": "verified_public",
      "value": {
        "identifier": "0000-0002-4331-4726",
        "url": "https://orcid.org/0000-0002-4331-4726"
      },
      "verified_at": "2026-08-09"
    },
    {
      "evidence": [
        "source.scopus.author_profile"
      ],
      "id": "profile.scopus",
      "kind": "academic_profile",
      "presentation_notes": "Use for identity and profile routing only; do not publish citation metrics, h-index, affiliation completeness, or publication completeness.",
      "status": "verified_public",
      "value": {
        "identifier": "57473761100",
        "url": "https://www.scopus.com/authid/detail.uri?authorId=57473761100"
      },
      "verified_at": "2026-08-09"
    },
    {
      "evidence": [
        "source.katru.faculty_profile"
      ],
      "id": "research.focus.ungrounded_power_systems",
      "kind": "research_focus",
      "presentation_notes": "Broad official-profile research areas only. This claim does not establish method effectiveness, validation results, publication completeness, or a stronger current-role statement.",
      "status": "verified_public",
      "value": {
        "areas": [
          "Insulation parameters in ungrounded electrical systems",
          "Energy efficiency in industrial power systems"
        ]
      },
      "verified_at": "2026-08-10"
    },
    {
      "evidence": [
        "source.owner_approval.v1_1_public_content"
      ],
      "id": "grant.ap22787517",
      "kind": "research_grant",
      "presentation_notes": "Approved for public display, but no sufficiently specific official public grant record was identified in this pass. Do not strengthen or extend the claim without a new source review.",
      "status": "owner_approved",
      "value": {
        "funding_program": "Young scientists",
        "grant_id": "AP22787517",
        "organization": "S. Seifullin KATRU",
        "period": {
          "end_year": 2026,
          "start_year": 2024
        },
        "project_title": "Development and testing of a prototype device for measuring insulation parameters in electrical networks with an isolated neutral",
        "role": "Principal Investigator"
      }
    },
    {
      "evidence": [
        "source.publication.isolated_neutral_article",
        "source.katru.faculty_profile"
      ],
      "id": "publication.isolated_neutral_experimental_studies",
      "kind": "publication",
      "presentation_notes": "The current site uses a minor readable title variant without the article 'the'. No citation or completeness claim is implied.",
      "status": "verified_public",
      "value": {
        "title": "Experimental studies of a developed method for determining the insulation parameters in a network with isolated neutral voltage up to 1000 V",
        "url": "https://bulletinofscience.kazatu.edu.kz/index.php/bulletinofscience/article/view/293",
        "year": 2019
      },
      "verified_at": "2026-08-09"
    },
    {
      "evidence": [
        "source.doi.gtd2_12436"
      ],
      "id": "publication.gtd2_12436",
      "kind": "publication",
      "presentation_notes": "Selected-work metadata only; no citation, metric, or completeness claim is implied.",
      "status": "verified_public",
      "value": {
        "doi": "10.1049/gtd2.12436",
        "title": "Mathematical description of the method for ungrounded AC systems to determine the network insulation",
        "url": "https://doi.org/10.1049/gtd2.12436",
        "year": 2022
      },
      "verified_at": "2026-08-09"
    },
    {
      "evidence": [
        "source.doi.icecet_9873012"
      ],
      "id": "publication.icecet_9873012",
      "kind": "publication",
      "presentation_notes": "Selected-work metadata only; no citation, metric, or completeness claim is implied.",
      "status": "verified_public",
      "value": {
        "doi": "10.1109/ICECET55527.2022.9873012",
        "title": "Experimental research of the developed method to determine the network insulation for ungrounded AC systems in laboratory conditions",
        "url": "https://doi.org/10.1109/ICECET55527.2022.9873012",
        "year": 2022
      },
      "verified_at": "2026-08-09"
    },
    {
      "evidence": [
        "source.doi.yiuh4401"
      ],
      "id": "publication.yiuh4401",
      "kind": "publication",
      "presentation_notes": "Selected-work metadata only; no citation, metric, or completeness claim is implied.",
      "status": "verified_public",
      "value": {
        "doi": "10.48081/YIUH4401",
        "title": "Approbation of the developed method for determining network insulation parameters on an operating excavator",
        "url": "https://doi.org/10.48081/YIUH4401",
        "year": 2023
      },
      "verified_at": "2026-08-09"
    },
    {
      "evidence": [
        "source.doi.kazatc_error_estimation"
      ],
      "id": "publication.kazatc_error_estimation",
      "kind": "publication",
      "presentation_notes": "Selected-work metadata only; no citation, metric, or completeness claim is implied.",
      "status": "verified_public",
      "value": {
        "doi": "10.52167/1609-1817-2023-125-2-428-436",
        "title": "Error estimation of the developed method for ungrounded AC systems to determine the network insulation",
        "url": "https://doi.org/10.52167/1609-1817-2023-125-2-428-436",
        "year": 2023
      },
      "verified_at": "2026-08-09"
    },
    {
      "evidence": [
        "source.eapo.patent_041128"
      ],
      "id": "patent.ea041128",
      "kind": "patent",
      "presentation_notes": "Material mismatch: the current RU/EN/KK site says this patent is valid in eight EAPO states, while the official record shows no continuing territory. EAPO labels 2022-09-16 as the patent publication date, not a separate grant date.",
      "status": "verified_public",
      "value": {
        "application_number": "202090923",
        "application_publication_date": "2021-11-30",
        "filing_date": "2020-05-08",
        "jurisdiction": "Eurasian Patent Organization",
        "legal_status": "not_in_force",
        "legal_status_checked_at": "2026-08-09",
        "patent_number": "EA 041128",
        "patent_publication_date": "2022-09-16",
        "publication_code": "B1",
        "subject_roles": [
          "applicant",
          "inventor",
          "patent_holder"
        ],
        "termination": {
          "date": "2023-05-09",
          "reason": "annual_fee_nonpayment"
        },
        "territorial_scope": {
          "contracting_states": [
            "AM",
            "AZ",
            "BY",
            "KG",
            "KZ",
            "RU",
            "TJ",
            "TM"
          ],
          "in_force_in": []
        },
        "title": "СПОСОБ ИЗМЕРЕНИЯ ПАРАМЕТРОВ ИЗОЛЯЦИИ ЭЛЕКТРИЧЕСКИХ СЕТЕЙ С ИЗОЛИРОВАННОЙ НЕЙТРАЛЬЮ НАПРЯЖЕНИЕМ ДО И ВЫШЕ 1000 В С УЧЕТОМ КВАДРАНТОВ КОМПЛЕКСНОЙ ПЛОСКОСТИ"
      },
      "verified_at": "2026-08-09"
    },
    {
      "evidence": [
        "source.qazpatent.patent_35922"
      ],
      "id": "patent.kz35922",
      "kind": "patent",
      "presentation_notes": "The historical patent record is verified, but its inactive status is not disclosed in the current presentation. Only the subject relationship is stored; other-person metadata from the official record is intentionally omitted.",
      "status": "verified_public",
      "value": {
        "application_number": "2021/0571.1",
        "bulletin_number": "42",
        "filing_date": "2021-09-22",
        "jurisdiction": "Kazakhstan",
        "legal_status": "not_in_force",
        "legal_status_checked_at": "2026-08-09",
        "patent_number": "35922",
        "publication_date": "2022-10-21",
        "subject_roles": [
          "inventor",
          "patent_holder"
        ],
        "termination": {
          "date": "2022-12-21",
          "reason": "early_termination_for_nonpayment"
        },
        "title": "Способ измерения параметров изоляции электрических сетей с изолированной нейтралью напряжением до и выше 1000 В с учетом симметричных составляющих"
      },
      "verified_at": "2026-08-09"
    },
    {
      "evidence": [
        "source.qazpatent.patent_37923"
      ],
      "id": "patent.kz37923",
      "kind": "patent",
      "presentation_notes": "The displayed application, dates, title, and institutional holder align with the official record. Only the subject relationship is stored; other-person metadata from the official record is intentionally omitted.",
      "status": "verified_public",
      "value": {
        "application_number": "2024/0964.1",
        "bulletin_number": "12",
        "filing_date": "2024-11-11",
        "jurisdiction": "Kazakhstan",
        "legal_status": "active",
        "legal_status_checked_at": "2026-08-09",
        "patent_holder": "S. Seifullin Kazakh Agrotechnical Research University",
        "patent_number": "37923",
        "publication_date": "2026-03-27",
        "subject_roles": [
          "inventor"
        ],
        "title": "Способ измерения несимметричных параметров изоляции в электрических сетях с изолированной нейтралью напряжением до и выше 1000 В с учетом метода симметричных составляющих"
      },
      "verified_at": "2026-08-09"
    },
    {
      "evidence": [
        "source.katru.faculty_profile",
        "source.owner_approval.v1_1_public_content",
        "source.owner_supplied.energy_auditor_certificate_review"
      ],
      "id": "credential.energy_auditor",
      "kind": "professional_credential",
      "presentation_notes": "The official KATRU profile publicly supports the general energy-auditor status. Sanitized review of owner-supplied private credential evidence supports the certified wording and the 2026-08-14 to 2029-08-06 term, but those fields have not been independently verified through a public registry or issuer page. The professional_practice_since value remains owner-approved. Certificate and accreditation identifiers, civil identifier, QR content, address, photo, signatures, seal, raw document, file name, path, and other private metadata are deliberately excluded.",
      "status": "partially_verified",
      "value": {
        "certificate_issued_on": "2026-08-14",
        "certificate_valid_until": "2029-08-06",
        "credential": "Certified energy auditor",
        "practice_area": "energy saving and energy efficiency improvement",
        "professional_practice_since": 2010
      },
      "verified_at": "2026-08-21"
    },
    {
      "evidence": [
        "source.katru.faculty_profile",
        "source.owner_approval.v1_1_public_content"
      ],
      "id": "award.keea.honoured_energy_worker",
      "kind": "award",
      "presentation_notes": "The official KATRU profile publicly supports the award, issuer, and year. The current English title and multilingual normalization remain owner-approved and require translation reconciliation.",
      "status": "partially_verified",
      "value": {
        "issuer": "Kazakhstan Electric Energy Association",
        "title": "Honoured Energy Worker",
        "year": 2016
      },
      "verified_at": "2026-08-09"
    },
    {
      "evidence": [
        "source.katru.faculty_profile",
        "source.owner_approval.v1_1_public_content"
      ],
      "id": "award.energy_ministry.honoured_energy_worker",
      "kind": "award",
      "presentation_notes": "The official KATRU profile publicly supports the award, issuer, and year. The current English title and multilingual normalization remain owner-approved and require translation reconciliation.",
      "status": "partially_verified",
      "value": {
        "issuer": "Ministry of Energy of the Republic of Kazakhstan",
        "title": "Honoured Energy Worker",
        "year": 2018
      },
      "verified_at": "2026-08-09"
    },
    {
      "evidence": [
        "source.katru.faculty_profile",
        "source.owner_approval.v1_1_public_content"
      ],
      "id": "award.energy_ministry.distinguished_power_engineer",
      "kind": "award",
      "presentation_notes": "The official KATRU profile publicly supports the award, issuer, and year. The current English title and multilingual normalization remain owner-approved and require translation reconciliation.",
      "status": "partially_verified",
      "value": {
        "issuer": "Ministry of Energy of the Republic of Kazakhstan",
        "title": "Distinguished Power Engineer",
        "year": 2023
      },
      "verified_at": "2026-08-09"
    },
    {
      "evidence": [
        "source.owner_approval.v1_1_public_content"
      ],
      "id": "award.energy_saving_contribution",
      "kind": "award",
      "presentation_notes": "Approved for public display. The generic issuer wording must not be strengthened without a reviewed public source.",
      "status": "owner_approved",
      "value": {
        "issuer": "Industry award",
        "title": "For contribution to energy saving",
        "year": 2024
      }
    },
    {
      "evidence": [
        "source.owner_approval.v1_1_public_content"
      ],
      "id": "project.ai_energy_auditor",
      "kind": "roadmap_project",
      "presentation_notes": "A public roadmap direction only; not a launched product, commercial platform, real AI service, or validated accuracy claim.",
      "status": "roadmap_only",
      "value": {
        "description": "Draft concept for AI-assisted energy audit with traceable reasoning",
        "name": "AI Energy Auditor",
        "stage": "in_development"
      }
    },
    {
      "evidence": [
        "source.owner_approval.v1_1_public_content"
      ],
      "id": "project.stm32_lab",
      "kind": "roadmap_project",
      "presentation_notes": "A public roadmap direction only; not a launched product, commercial platform, or validated performance claim.",
      "status": "roadmap_only",
      "value": {
        "description": "Hardware signal capture and a measurement test bench",
        "name": "STM32 / measurement lab",
        "stage": "in_development"
      }
    }
  ],
  "contract_id": "public-ai-assistant-v0",
  "policy": {
    "allowed_claim_statuses": [
      "verified_public",
      "partially_verified",
      "owner_approved",
      "roadmap_only"
    ],
    "citation_source_ids_must_match_claim_evidence": true,
    "citations_must_match_request_context": true,
    "refusal_categories": [
      "private_identifier",
      "private_contact_or_address",
      "raw_or_unpublished_material",
      "unsupported_inference",
      "out_of_scope",
      "prompt_injection",
      "insufficient_public_evidence",
      "service_unavailable"
    ],
    "status_language_rules": {
      "owner_approved": "identify as owner-approved when the distinction matters",
      "partially_verified": "do not strengthen beyond the reviewed claim wording",
      "roadmap_only": "always describe as in development or a concept, never as launched"
    }
  },
  "relations": [
    {
      "evidence": [
        "source.katru.faculty_profile",
        "source.astana_energy.board_profile"
      ],
      "from": "person.iskander_kurabayev",
      "id": "relation.person.holds_role.university_current",
      "note": "Role and organization only; the disputed start date remains unresolved and is excluded from the generated CV.",
      "predicate": "holds_role",
      "status": "partially_verified",
      "to": "role.university.current"
    },
    {
      "evidence": [
        "source.astana_energy.board_profile"
      ],
      "from": "person.iskander_kurabayev",
      "id": "relation.person.holds_role.astana_energy_current",
      "note": "Point-in-time current role; currentness must be rechecked before later publication updates.",
      "predicate": "holds_role",
      "status": "verified_public",
      "to": "role.astana_energy.current"
    },
    {
      "evidence": [
        "source.katru.faculty_profile",
        "source.astana_energy.board_profile"
      ],
      "from": "person.iskander_kurabayev",
      "id": "relation.person.holds_credential.education_phd",
      "predicate": "holds_credential",
      "status": "verified_public",
      "to": "education.phd.electrical_complexes_systems"
    },
    {
      "evidence": [
        "source.katru.faculty_profile",
        "source.astana_energy.board_profile"
      ],
      "from": "person.iskander_kurabayev",
      "id": "relation.person.holds_credential.education_master",
      "predicate": "holds_credential",
      "status": "verified_public",
      "to": "education.master.electrical_power_engineering"
    },
    {
      "evidence": [
        "source.katru.faculty_profile",
        "source.astana_energy.board_profile"
      ],
      "from": "person.iskander_kurabayev",
      "id": "relation.person.holds_credential.education_specialist",
      "predicate": "holds_credential",
      "status": "verified_public",
      "to": "education.specialist.industrial_power_supply"
    },
    {
      "evidence": [
        "source.katru.faculty_profile",
        "source.owner_approval.v1_1_public_content"
      ],
      "from": "person.iskander_kurabayev",
      "id": "relation.person.holds_credential.energy_auditor",
      "predicate": "holds_credential",
      "status": "partially_verified",
      "to": "credential.energy_auditor"
    },
    {
      "evidence": [
        "source.publication.isolated_neutral_article",
        "source.katru.faculty_profile"
      ],
      "from": "person.iskander_kurabayev",
      "id": "relation.person.authored.isolated_neutral_experimental_studies",
      "predicate": "authored",
      "status": "verified_public",
      "to": "publication.isolated_neutral_experimental_studies"
    },
    {
      "evidence": [
        "source.doi.gtd2_12436"
      ],
      "from": "person.iskander_kurabayev",
      "id": "relation.person.authored.gtd2_12436",
      "predicate": "authored",
      "status": "verified_public",
      "to": "publication.gtd2_12436"
    },
    {
      "evidence": [
        "source.doi.icecet_9873012"
      ],
      "from": "person.iskander_kurabayev",
      "id": "relation.person.authored.icecet_9873012",
      "predicate": "authored",
      "status": "verified_public",
      "to": "publication.icecet_9873012"
    },
    {
      "evidence": [
        "source.doi.yiuh4401"
      ],
      "from": "person.iskander_kurabayev",
      "id": "relation.person.authored.yiuh4401",
      "predicate": "authored",
      "status": "verified_public",
      "to": "publication.yiuh4401"
    },
    {
      "evidence": [
        "source.doi.kazatc_error_estimation"
      ],
      "from": "person.iskander_kurabayev",
      "id": "relation.person.authored.kazatc_error_estimation",
      "predicate": "authored",
      "status": "verified_public",
      "to": "publication.kazatc_error_estimation"
    },
    {
      "evidence": [
        "source.eapo.patent_041128"
      ],
      "from": "person.iskander_kurabayev",
      "id": "relation.person.inventor_on.ea041128",
      "note": "Historical inventor relationship; the canonical claim records that the patent is not in force.",
      "predicate": "inventor_on",
      "status": "verified_public",
      "to": "patent.ea041128"
    },
    {
      "evidence": [
        "source.qazpatent.patent_35922"
      ],
      "from": "person.iskander_kurabayev",
      "id": "relation.person.inventor_on.kz35922",
      "note": "Historical inventor relationship; the canonical claim records that the patent is not in force.",
      "predicate": "inventor_on",
      "status": "verified_public",
      "to": "patent.kz35922"
    },
    {
      "evidence": [
        "source.qazpatent.patent_37923"
      ],
      "from": "person.iskander_kurabayev",
      "id": "relation.person.inventor_on.kz37923",
      "note": "Inventor relationship and legal status are point-in-time public facts.",
      "predicate": "inventor_on",
      "status": "verified_public",
      "to": "patent.kz37923"
    },
    {
      "evidence": [
        "source.owner_approval.v1_1_public_content"
      ],
      "from": "person.iskander_kurabayev",
      "id": "relation.person.leads.ap22787517",
      "note": "Publicly approved leadership claim; independent grant verification remains incomplete.",
      "predicate": "leads",
      "status": "owner_approved",
      "to": "grant.ap22787517"
    },
    {
      "evidence": [
        "source.katru.faculty_profile",
        "source.owner_approval.v1_1_public_content"
      ],
      "from": "person.iskander_kurabayev",
      "id": "relation.person.received_award.keea_honoured_energy_worker",
      "predicate": "received_award",
      "status": "partially_verified",
      "to": "award.keea.honoured_energy_worker"
    },
    {
      "evidence": [
        "source.katru.faculty_profile",
        "source.owner_approval.v1_1_public_content"
      ],
      "from": "person.iskander_kurabayev",
      "id": "relation.person.received_award.energy_ministry_honoured_energy_worker",
      "predicate": "received_award",
      "status": "partially_verified",
      "to": "award.energy_ministry.honoured_energy_worker"
    },
    {
      "evidence": [
        "source.katru.faculty_profile",
        "source.owner_approval.v1_1_public_content"
      ],
      "from": "person.iskander_kurabayev",
      "id": "relation.person.received_award.distinguished_power_engineer",
      "predicate": "received_award",
      "status": "partially_verified",
      "to": "award.energy_ministry.distinguished_power_engineer"
    },
    {
      "evidence": [
        "source.owner_approval.v1_1_public_content"
      ],
      "from": "person.iskander_kurabayev",
      "id": "relation.person.received_award.energy_saving_contribution",
      "predicate": "received_award",
      "status": "owner_approved",
      "to": "award.energy_saving_contribution"
    },
    {
      "evidence": [
        "source.owner_approval.v1_1_public_content"
      ],
      "from": "person.iskander_kurabayev",
      "id": "relation.person.develops.ai_energy_auditor",
      "note": "In development; not a launched product or real AI service.",
      "predicate": "develops",
      "status": "roadmap_only",
      "to": "project.ai_energy_auditor"
    },
    {
      "evidence": [
        "source.owner_approval.v1_1_public_content"
      ],
      "from": "person.iskander_kurabayev",
      "id": "relation.person.develops.stm32_lab",
      "note": "In development; no validated performance claim is implied.",
      "predicate": "develops",
      "status": "roadmap_only",
      "to": "project.stm32_lab"
    },
    {
      "evidence": [
        "source.katru.faculty_profile"
      ],
      "from": "research.focus.ungrounded_power_systems",
      "id": "relation.research_focus.addresses_topic.insulation_parameters",
      "predicate": "addresses_topic",
      "status": "verified_public",
      "to": "topic.insulation_parameters"
    },
    {
      "evidence": [
        "source.katru.faculty_profile"
      ],
      "from": "research.focus.ungrounded_power_systems",
      "id": "relation.research_focus.addresses_topic.energy_efficiency",
      "predicate": "addresses_topic",
      "status": "verified_public",
      "to": "topic.energy_efficiency"
    },
    {
      "evidence": [
        "source.publication.isolated_neutral_article",
        "source.katru.faculty_profile"
      ],
      "from": "publication.isolated_neutral_experimental_studies",
      "id": "relation.publication.isolated_neutral_studies.addresses_topic.insulation_parameters",
      "predicate": "addresses_topic",
      "status": "verified_public",
      "to": "topic.insulation_parameters"
    },
    {
      "evidence": [
        "source.doi.gtd2_12436"
      ],
      "from": "publication.gtd2_12436",
      "id": "relation.publication.gtd2_12436.addresses_topic.isolated_neutral_networks",
      "predicate": "addresses_topic",
      "status": "verified_public",
      "to": "topic.isolated_neutral_networks"
    },
    {
      "evidence": [
        "source.doi.icecet_9873012"
      ],
      "from": "publication.icecet_9873012",
      "id": "relation.publication.icecet_9873012.addresses_topic.measurement_diagnostics",
      "predicate": "addresses_topic",
      "status": "verified_public",
      "to": "topic.measurement_diagnostics"
    },
    {
      "evidence": [
        "source.doi.yiuh4401"
      ],
      "from": "publication.yiuh4401",
      "id": "relation.publication.yiuh4401.addresses_topic.measurement_diagnostics",
      "predicate": "addresses_topic",
      "status": "verified_public",
      "to": "topic.measurement_diagnostics"
    },
    {
      "evidence": [
        "source.doi.kazatc_error_estimation"
      ],
      "from": "publication.kazatc_error_estimation",
      "id": "relation.publication.kazatc_error_estimation.addresses_topic.insulation_parameters",
      "predicate": "addresses_topic",
      "status": "verified_public",
      "to": "topic.insulation_parameters"
    },
    {
      "evidence": [
        "source.eapo.patent_041128"
      ],
      "from": "patent.ea041128",
      "id": "relation.patent.ea041128.addresses_topic.isolated_neutral_networks",
      "predicate": "addresses_topic",
      "status": "verified_public",
      "to": "topic.isolated_neutral_networks"
    },
    {
      "evidence": [
        "source.qazpatent.patent_35922"
      ],
      "from": "patent.kz35922",
      "id": "relation.patent.kz35922.addresses_topic.symmetrical_components",
      "predicate": "addresses_topic",
      "status": "verified_public",
      "to": "topic.symmetrical_components"
    },
    {
      "evidence": [
        "source.qazpatent.patent_37923"
      ],
      "from": "patent.kz37923",
      "id": "relation.patent.kz37923.addresses_topic.symmetrical_components",
      "predicate": "addresses_topic",
      "status": "verified_public",
      "to": "topic.symmetrical_components"
    },
    {
      "evidence": [
        "source.owner_approval.v1_1_public_content"
      ],
      "from": "grant.ap22787517",
      "id": "relation.grant.ap22787517.addresses_topic.isolated_neutral_networks",
      "predicate": "addresses_topic",
      "status": "owner_approved",
      "to": "topic.isolated_neutral_networks"
    },
    {
      "evidence": [
        "source.owner_approval.v1_1_public_content"
      ],
      "from": "grant.ap22787517",
      "id": "relation.grant.ap22787517.addresses_topic.measurement_diagnostics",
      "predicate": "addresses_topic",
      "status": "owner_approved",
      "to": "topic.measurement_diagnostics"
    },
    {
      "evidence": [
        "source.katru.faculty_profile",
        "source.owner_approval.v1_1_public_content"
      ],
      "from": "credential.energy_auditor",
      "id": "relation.credential.energy_auditor.addresses_topic.energy_audit",
      "predicate": "addresses_topic",
      "status": "partially_verified",
      "to": "topic.energy_audit"
    },
    {
      "evidence": [
        "source.katru.faculty_profile",
        "source.owner_approval.v1_1_public_content"
      ],
      "from": "credential.energy_auditor",
      "id": "relation.credential.energy_auditor.addresses_topic.energy_efficiency",
      "predicate": "addresses_topic",
      "status": "partially_verified",
      "to": "topic.energy_efficiency"
    },
    {
      "evidence": [
        "source.owner_approval.v1_1_public_content"
      ],
      "from": "project.ai_energy_auditor",
      "id": "relation.project.ai_energy_auditor.addresses_topic.energy_audit",
      "predicate": "addresses_topic",
      "status": "roadmap_only",
      "to": "topic.energy_audit"
    },
    {
      "evidence": [
        "source.owner_approval.v1_1_public_content"
      ],
      "from": "project.ai_energy_auditor",
      "id": "relation.project.ai_energy_auditor.addresses_topic.ai_assisted_engineering",
      "predicate": "addresses_topic",
      "status": "roadmap_only",
      "to": "topic.ai_assisted_engineering"
    },
    {
      "evidence": [
        "source.owner_approval.v1_1_public_content"
      ],
      "from": "project.stm32_lab",
      "id": "relation.project.stm32_lab.addresses_topic.embedded_measurement_systems",
      "predicate": "addresses_topic",
      "status": "roadmap_only",
      "to": "topic.embedded_measurement_systems"
    },
    {
      "evidence": [
        "source.owner_approval.v1_1_public_content"
      ],
      "from": "project.stm32_lab",
      "id": "relation.project.stm32_lab.addresses_topic.measurement_diagnostics",
      "predicate": "addresses_topic",
      "status": "roadmap_only",
      "to": "topic.measurement_diagnostics"
    }
  ],
  "reviewed_at": "2026-09-02",
  "schema_version": "0.1",
  "source_hashes": {
    "data/public-ai-contract.json": "ae463689f926c8da741ac8f46c860abcac8bdaf9d0e3d49998d51672a5cd418c",
    "data/public-facts.json": "999844b4f5d3b4f3a40442f892e1219831e8ab32b6c9e5b9bfbefd158cff0ff8",
    "data/public-research-graph.json": "875c59db3f9f2c6faba4f08fe3d12285281b65205fde340e73ecfce85e970d9a"
  },
  "sources": [
    {
      "authority": "ORCID",
      "checked_at": "2026-08-09",
      "id": "source.orcid.public_record",
      "kind": "public_profile",
      "source_role": "primary_identity",
      "url": "https://orcid.org/0000-0002-4331-4726"
    },
    {
      "authority": "S. Seifullin Kazakh Agrotechnical Research University",
      "checked_at": "2026-08-10",
      "id": "source.katru.faculty_profile",
      "kind": "official_institutional_profile",
      "source_role": "primary_institutional",
      "url": "https://kazatu.edu.kz/ru/pps/kurabaev-iskander-kazbekovic"
    },
    {
      "authority": "repository_owner",
      "checked_at": "2026-08-23",
      "id": "source.owner_approval.kazakh_display_name",
      "kind": "owner_approval",
      "public_safe_note": "Confirms the exact Kazakh full name approved for public display. This is authoritative owner approval, not independent public verification.",
      "source_role": "kazakh_identity_canonicalization"
    },
    {
      "authority": "Astana-Energy JSC",
      "checked_at": "2026-08-10",
      "id": "source.astana_energy.board_profile",
      "kind": "official_institutional_profile",
      "source_role": "primary_institutional",
      "url": "https://astana-energy.kz/ru/o-kompanii/sovet-direktorov/kurabaev-iskander-kazbekovich"
    },
    {
      "authority": "Scopus",
      "checked_at": "2026-08-09",
      "id": "source.scopus.author_profile",
      "kind": "public_profile",
      "source_role": "identity_disambiguation",
      "url": "https://www.scopus.com/authid/detail.uri?authorId=57473761100"
    },
    {
      "authority": "repository_owner",
      "checked_at": "2026-08-09",
      "id": "source.owner_approval.v1_1_public_content",
      "kind": "owner_approval",
      "public_safe_note": "Confirms approval of the current visible public content; does not independently verify factual currentness.",
      "source_role": "publication_approval"
    },
    {
      "authority": "Eurasian Agrotechnical Journal",
      "checked_at": "2026-08-09",
      "id": "source.publication.isolated_neutral_article",
      "kind": "publisher_page",
      "source_role": "publication_metadata",
      "url": "https://bulletinofscience.kazatu.edu.kz/index.php/bulletinofscience/article/view/293"
    },
    {
      "authority": "DOI and publisher metadata",
      "checked_at": "2026-08-09",
      "id": "source.doi.gtd2_12436",
      "kind": "doi_metadata",
      "source_role": "publication_metadata",
      "url": "https://doi.org/10.1049/gtd2.12436"
    },
    {
      "authority": "DOI and publisher metadata",
      "checked_at": "2026-08-09",
      "id": "source.doi.icecet_9873012",
      "kind": "doi_metadata",
      "source_role": "publication_metadata",
      "url": "https://doi.org/10.1109/ICECET55527.2022.9873012"
    },
    {
      "authority": "DOI and publisher metadata",
      "checked_at": "2026-08-09",
      "id": "source.doi.yiuh4401",
      "kind": "doi_metadata",
      "source_role": "publication_metadata",
      "url": "https://doi.org/10.48081/YIUH4401"
    },
    {
      "authority": "DOI and publisher metadata",
      "checked_at": "2026-08-09",
      "id": "source.doi.kazatc_error_estimation",
      "kind": "doi_metadata",
      "source_role": "publication_metadata",
      "url": "https://doi.org/10.52167/1609-1817-2023-125-2-428-436"
    },
    {
      "authority": "Eurasian Patent Organization",
      "checked_at": "2026-08-09",
      "id": "source.eapo.patent_041128",
      "kind": "official_patent_registry",
      "source_role": "primary_legal_status",
      "url": "https://www.eapo.org/pubservices/info/registry/inventions/patents/041128?ipType=InventionPatentCase"
    },
    {
      "authority": "Qazpatent",
      "checked_at": "2026-08-09",
      "id": "source.qazpatent.patent_35922",
      "kind": "official_patent_registry",
      "source_role": "primary_legal_status",
      "url": "https://gosreestr.kazpatent.kz/Invention/Details?docNumber=347854"
    },
    {
      "authority": "Qazpatent",
      "checked_at": "2026-08-09",
      "id": "source.qazpatent.patent_37923",
      "kind": "official_patent_registry",
      "source_role": "primary_legal_status",
      "url": "https://gosreestr.kazpatent.kz/Invention/Details?docNumber=411423"
    },
    {
      "authority": "repository_owner",
      "checked_at": "2026-08-21",
      "id": "source.owner_supplied.energy_auditor_certificate_review",
      "kind": "owner_supplied_document_review",
      "public_safe_note": "Sanitized review confirms only the certified-energy-auditor wording, issue date, and validity end date approved for public display. Private artifact and document metadata are intentionally excluded; this is not independent public verification.",
      "source_role": "credential_issue_and_validity"
    }
  ],
  "subject": "person.iskander_kurabayev",
  "topics": [
    {
      "id": "topic.insulation_parameters",
      "kind": "research_topic",
      "labels": {
        "en": "Insulation parameters",
        "ru": "Параметры изоляции"
      },
      "public": true
    },
    {
      "id": "topic.energy_efficiency",
      "kind": "research_topic",
      "labels": {
        "en": "Energy efficiency",
        "ru": "Энергоэффективность"
      },
      "public": true
    },
    {
      "id": "topic.isolated_neutral_networks",
      "kind": "research_topic",
      "labels": {
        "en": "Isolated-neutral and ungrounded electrical networks",
        "ru": "Электрические сети с изолированной нейтралью"
      },
      "public": true
    },
    {
      "id": "topic.measurement_diagnostics",
      "kind": "research_topic",
      "labels": {
        "en": "Electrical measurement and diagnostics",
        "ru": "Электрические измерения и диагностика"
      },
      "public": true
    },
    {
      "id": "topic.symmetrical_components",
      "kind": "research_topic",
      "labels": {
        "en": "Symmetrical components",
        "ru": "Симметричные составляющие"
      },
      "public": true
    },
    {
      "id": "topic.energy_audit",
      "kind": "research_topic",
      "labels": {
        "en": "Energy audit",
        "ru": "Энергоаудит"
      },
      "public": true
    },
    {
      "id": "topic.ai_assisted_engineering",
      "kind": "research_topic",
      "labels": {
        "en": "AI-assisted engineering",
        "ru": "AI-ассистированные инженерные процессы"
      },
      "public": true
    },
    {
      "id": "topic.embedded_measurement_systems",
      "kind": "research_topic",
      "labels": {
        "en": "Embedded measurement systems",
        "ru": "Встраиваемые измерительные системы"
      },
      "public": true
    }
  ]
}
);
